config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :notes
  root 'notes#index'
end

app/models/note.rb
# frozen_string_literal: true

class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :body, type: String
  field :tags, type: Array

  scope :search_by_title, ->(title) { where(title: /.*#{title}.*/i) }
  scope :search_by_tag, ->(tag) { where(tags: /.*#{tag}.*/i) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

# Notes controller
class NotesController < ApplicationController
  before_action :fetch_note, only: %i[show edit update destroy]

  def index
    @note = Note.new
    @notes = Note.order(created_at: :desc).all
    if params[:note]
      search_by = params[:note][:search]
      by_title = @notes.search_by_title(search_by)
      by_tag = @notes.search_by_tag(search_by)
      @notes = by_title.empty? ? by_tag : by_title
    end
  end

  def create
    note = tag_format note_params
    note[:tags] = params[:note][:tags].split(',')
    note = Note.create(note)
    if note.save
      flash[:success] = 'Note created Successfully.'
    else
      flash[:danger] = 'Failed to create Note.'
    end
    redirect_to note_path(note)
  end

  def show; end

  def edit; end

  def update
    note = tag_format note_params
    note = @note.update_attributes(note)
    if note
      flash[:success] = 'Note updated Successfully.'
    else
      flash[:danger] = 'Failed to update Note.'
    end
    redirect_to note_path(@note)
  end

  def destroy
    @note.destroy
    flash[:danger] = 'Note Deleted Successfuly'
    redirect_to root_path
  end

  def note_params
    params.require(:note).permit(:title, :body, :tags)
  end

  def fetch_note
    @note = Note.find(params[:id])
  end

  def tag_format(prms)
    prms[:tags] = params[:note][:tags].split(' ')
    prms
  end

  private :fetch_note, :note_params, :tag_format
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNotesApplication</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'notes/navbar'%>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield(:alert) %>
    <%= yield %>
    <%= render template: 'notes/new'%>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note, html: {class: 'form-horizontal'} do |f| %>
  <div class="modal-body">
    <div class="form-group">
      <%= f.label :title, class: "col-sm-2 control-label"%>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control", placeholder: "Name your note", required: true%>
      </div>
    </div>
     <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label"%>
      <div class="col-sm-10">
        <%= f.text_area :body, class: "form-control", rows: "10", placeholder: "What would you like to note?", required: true%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :tags, class: "col-sm-2 control-label"%>
      <div class="col-sm-10">
        <%= f.text_field :tags, class: "form-control", placeholder: "TagA TagB", required: true%>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
<% end %>

app/views/notes/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path%>">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="nav navbar-nav navbar-right">
        <%= form_for :note, url: root_path, method: :get do %>
          <input class="form-control" type="text" name="note[search]", placeholder="Search by tag or title" aria-label="Search">
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/notes/index.html.erb
<div class="well">
 
  <h4>Taking notes is an important part of the life of every student. </h4>
  <li>When you are reading or listening, taking notes helps you concentrate.</li>
  <li>Notes help you to maintain a permanent record of what you have read or listened to.</li>

</div>

<div class="container">
  <div>
    <form>
      <a href="#" class="btn btn-success navbar-btn btn-sm" 
        data-toggle="modal" data-target="#new-note-modal">Create Note
      </a>
    </form>
  </div>
  
  <div class="notes">
    <% @notes.each do |note| %>
      <div class="media" data-target="<%= note_path(note) %>">
        <div class="media-body cont">
          <h3 class="media-heading"><span style="color:Red"><%= note.title%></span></h3>
            <div class="time hidden-xs"><%= time_ago_in_words note.created_at%> ago</div>
            <br />
            <div class="body"><%= truncate note.body, length: 300 %></div>
            <br />
            <div id="tags-div">
              <p class="tags-label">Tags </p>
            </div>&nbsp
            <div id="block_container">
              <% note.tags.each do |tag|%>
                <% if tag == note.tags.last %>
                  <%= tag %>
                <% else %>
                  <%= tag%>,
                <% end %>
              <% end %>
            </div>
            <div class="hidden-xs">
              <br /><a href="<%= note_path(note) %>" class="btn btn-success btn-xs" %>
              View note </a>
            </div>
        </div>
      </div>
    <% end %>
  </div>

  <% if @notes.empty?%>
    <div class="alert alert-info"> Nothing here Yet. Create the First Note.</div>
  <% end %>
</div>

app/views/notes/new.html.erb
<!-- Modal -->
<div class="modal fade" id="new-note-modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="new-note-modal">Notes</h5>
      </div>
      <%= render 'form'%>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="container note">
  <div class="lead well cont">
    <div>
      <div class="media-body">
        <h3 class="media-heading"><span style="color:Red"><%= @note.title%></span></h3>
        <br />
        <div class="body"> <%= @note.body %></div>
        <br />
        <div id="tags-div">
          <p class="tags-label-show">Tags </p>
        </div>&nbsp
        <div id="block_container">
          <% @note.tags.each do |tag|%>
            <% if tag == @note.tags.last %>
              <%= tag %>
            <% else %>
              <%= tag%>,
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'Edit', edit_note_path(@note), class: "btn btn-info",
    data: { toggle: "modal", target: "#new-note-modal" } 
  %>
  <span style="float:right"><%= link_to 'Delete', note_path(@note.id),
    class: "btn btn-danger",
    method: :delete,
    data: { confirm: 'Are you sure?' }
  %> </span>
</div>